import React from 'react';
import { View, Text, StyleSheet, Dimensions } from 'react-native';
const { width } = Dimensions.get('window');
const itemWidth = (width / 5) * 2;
const gap = (width - itemWidth) / 8;


export const styles = StyleSheet.create({
    HomeWrapper: {
        flex: 1,
        backgroundColor: "#FFFFFF",
    },
    HeaderContainer: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        height: 160,
        backgroundColor: "#ffffff000",
    },
    searchWrapper: {
        alignContent: "center",
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 8,
        paddingLeft: 20,
        paddingRight: 20,
        flexDirection: 'row',
        width: "100%",
        marginTop: "5%",
    },
    makeRowtheSearch: {
        backgroundColor: '#F7F7F7',
        borderRadius: 5,
        width: "80%",
        shadowColor: "#000",
        shadowOpacity: 0.5,
        shadowRadius: 5,
        elevation: 8,
        flexDirection: "row",
        // justifyContent: 'center',
        alignContent: "center",
        alignItems: 'center',
        paddingLeft: 10,
        paddingRight: 10,
    },
    SearchIcon: {
        paddingRight: 10,
    },
    textInSearch: {
        paddingRight: 10,
        color: "#C6C6C6",
    },
    filterArea: {
        backgroundColor: "#EF3340",
        // height: "70%",
        padding: 5,
        width: "8%",
        // justifyContent: 'center',
        alignItems: 'center',
        alignItems: 'center',
        borderRadius: 5,
    },
    cardImg: {
        height: 25,
        width: 25,
        alignSelf: 'center',
    },
    categoryContainer: {
        flexDirection: 'row',
        width: '100%',
        alignSelf: 'center',
        marginTop: 10,
        marginBottom: 10,
    },
    cusineWrapper: {
        paddingLeft: "2%",
    },
    cusineTxt: {
        color: '#000',
        marginTop: "5%",
        fontSize: 16,
        fontWeight: 'bold',
    },
    categoryBtn: {
        flex: 1,
        width: '70%',
        marginRight: 15,
        alignSelf: 'center',
    },
    categoryIcon: {
        borderWidth: 0,
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
        width: 80,
        height: 80,
        backgroundColor: '#76e8b7' /* '#FF6347' */,
        borderRadius: 50,
        // borderWidth: 2,
        borderColor: '#03befc',
    },
    bubbleImg: {
        height: '100%',
        width: '100%',
        alignSelf: 'center',
        borderRadius: 50,
        borderBottomRightRadius: 50,
        borderTopRightRadius: 50,
    },
    categoryBtnTxt: {
        alignSelf: 'center',
        marginTop: 5,
        fontSize: 14,
        fontFamily: "arial",
        fontWeight: 'bold',
        color: '#333',
    },
    FeaturedWrapper: {
    },
    featureText: {
        // backgroundColor: "pink",
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: "90%",
        alignSelf: 'center',
    },
    featureSmalltxt: {
        fontSize: 12,
    },
    yellowText: {
        color: "#FFC145",
        fontWeight: 'bold',
    },
    //Tile Scrolling

    scrollView: {
        paddingLeft: "5%",
        paddingRight: "10%",
        alignItems: 'center',
        marginVertical: "5%",
    },
    item: {
        height: (itemWidth / 2) * 1.8,
        width: itemWidth * 1.5,
        marginRight: gap,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    uniqueSliderIMg: {
        height: '100%',
        width: '100%',
        alignSelf: 'center',
        borderRadius: 10,
    },
    sliderImg: {
        height: '100%',
        width: '100%',
        alignSelf: 'center',
        borderTopLeftRadius: 15,
        borderTopRightRadius: 15,
    },
    cardSliderWrapper: {
        // backgroundColor: "pink",
        flexDirection: 'row',
        marginTop: "5%",
        marginBottom: "5%",
        paddingTop: "5%",
        paddingBottom: "5%",
    },
    cardSlider: {
        backgroundColor: "#FFFFFF",
        alignSelf: 'center',
        width: '60%',
        height: 350,
        borderRadius: 15,
        shadowColor: "#000",
        shadowOpacity: 0.5,
        shadowRadius: 5,
        elevation: 15,
        marginHorizontal: 20,

    },
    cardThinSlider: {
        backgroundColor: "#FFFFFF",
        alignSelf: 'center',
        width: '45%',
        height: 300,
        borderRadius: 15,
        shadowColor: "#000",
        shadowOpacity: 0.5,
        shadowRadius: 5,
        elevation: 15,
        marginHorizontal: 10,
        marginVertical: 10,
    },
    RecommendCard: {
        backgroundColor: "#FFFFFF",
        alignSelf: 'center',
        width: '45%',
        height: 250,
        borderRadius: 15,
        shadowColor: "#000",
        shadowOpacity: 0.5,
        shadowRadius: 5,
        elevation: 15,
        marginHorizontal: 10,
        marginVertical: 10,
        top: -70,
        // position: 'absolute',
    },
    RecommendCardZero: {
        backgroundColor: "#FFFFFF",
        alignSelf: 'center',
        width: '45%',
        height: 250,
        borderRadius: 15,
        shadowColor: "#000",
        shadowOpacity: 0.5,
        shadowRadius: 5,
        elevation: 15,
        marginHorizontal: 10,
        marginVertical: 10,
        bottom: "5%",
        // position: 'absolute',
    },
    cardSiderImage: {
        height: "55%",
        width: "100%",
    },
    recommendedcCrdSiderImage: {
        height: "100%",
        width: "100%",
        borderRadius: 15,
    },
    recommendedsliderImg: {
        height: '100%',
        width: '100%',
        alignSelf: 'center',
        borderRadius: 15,
    },
    alternateRecommendCard: {
        backgroundColor: "#FFFFFF",
        alignSelf: 'center',
        width: '45%',
        height: 300,
        borderRadius: 15,
        shadowColor: "#000",
        shadowOpacity: 0.5,
        shadowRadius: 5,
        elevation: 15,
        marginHorizontal: 10,
        marginVertical: 10,
    },
    cardDetail: {
        height: "45%",
        paddingTop: 20,
        width: "100%",
        padding: "5%",
        justifyContent: 'space-between',
    },
    CardHeadingSlider: {
        color: "#000",
        fontWeight: 'bold',
    },
    cardSubHeading: {
        color: "#010101",
        fontSize: 12,
        fontWeight: "500",
    },
    ThreeRow: {
        flexDirection: "row",
        justifyContent: 'space-between',
    },
    IconAndText: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    flexStartText: {
        flexDirection: 'row',
        width: "60%",
        justifyContent: 'space-between',
    },
    MakeCircle: {
        borderWidth: 1,
        width: 15,
        height: 15,
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center',
        borderColor: "#5A5A5A",
        borderRadius: 10,
    },
    smallTexticon: {
        fontSize: 15,
    },
    smallText: {
        fontWeight: 'bold',
        marginHorizontal: 5,
        fontSize: 11,
    },
    HeartICon: {
        position: 'absolute',
        right: 0,
        padding: 10,
    },
    IconCircle: {
        backgroundColor: 'rgba(255, 255, 255, 0.6)',
        padding: 10,
        borderRadius: 50,
    },
    greenBack: {
        backgroundColor: "#4EC33B",
        paddingHorizontal: 10,
        borderRadius: 10,
        justifyContent: 'center',
    },
    WhiteText: {
        color: "#FFFFFF",
        fontSize: 11,
    },
    TwoCard: {
        // flexDirection: 'row',
        // backgroundColor: "red",
        width: "100%",
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 25,
        // paddingBottom: 25,
    },
    RecommendTwoCard: {
        // flexDirection: 'row',
        width: "100%",
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 25,
        // paddingBottom: 25,
    },
    downTheText: {
        height: "100%",
        padding: 10,
        paddingBottom: "15%",
        justifyContent: 'flex-end',
        // alignItems : 'center',
        // bottom: 10,
    },
    recomendHeadTxt: {
        color: "#FFFFFF",
        fontSize: 14,
        fontWeight: 'bold',
        marginBottom: "5%",
    },
    recomendSubHeadTxt: {
        color: "#646463",
        fontSize: 10,
        fontWeight: 'bold',
    },
    WhiteTxtHeader: {
        color: "#fff",
        fontSize: 10,
        fontWeight: 'bold',
    },
    WhiteTxtHeaderHeading: {
        color: "#fff",
        fontSize: 14,
        fontWeight: 'bold',
    },
    HeaderContainer: {
        flexDirection: "row",
        alignItems: "center",
        // justifyContent: "space-between",
        height: 160,
        backgroundColor: "#ffffff000",
    },
    ImageContent: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    HeaderDetail: {
        flexDirection: "row",
        width: "100%",
        // alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 15,
        bottom: -40,
    }
});
